// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    NavBar: typeof import("./src/components/NavBar/index.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    SvgIcon: typeof import("./src/components/SvgIcon/index.vue")["default"];
    Tabbar: typeof import("./src/components/Tabbar/index.vue")["default"];
    VanBadge: typeof import("vant/es")["Badge"];
    VanButton: typeof import("vant/es")["Button"];
    VanCard: typeof import("vant/es")["Card"];
    VanConfigProvider: typeof import("vant/es")["ConfigProvider"];
    VanDivider: typeof import("vant/es")["Divider"];
    VanEmpty: typeof import("vant/es")["Empty"];
    VanField: typeof import("vant/es")["Field"];
    VanFloatingBubble: typeof import("vant/es")["FloatingBubble"];
    VanLoading: typeof import("vant/es")["Loading"];
    VanNavBar: typeof import("vant/es")["NavBar"];
    VanPopup: typeof import("vant/es")["Popup"];
    VanSearch: typeof import("vant/es")["Search"];
    VanTab: typeof import("vant/es")["Tab"];
    VanTabbar: typeof import("vant/es")["Tabbar"];
    VanTabbarItem: typeof import("vant/es")["TabbarItem"];
    VanTabs: typeof import("vant/es")["Tabs"];
    VanToast: typeof import("vant/es")["Toast"];
    VanDialog: typeof import("vant/es")["Dialog"];
    VanShowToast: typeof import("vant/es")["showToast"];
  }
}
